CREATE TABLE IF NOT EXISTS sekai_memory_book_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(1000),
    phone_number VARCHAR(20),
    membership_plan VARCHAR(20) NOT NULL DEFAULT 'FREE',
    pro_expire_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_memory_user_username UNIQUE (username),
    CONSTRAINT uk_memory_user_phone_number UNIQUE (phone_number)
);

CREATE TABLE IF NOT EXISTS sekai_memory_book_anime (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    type VARCHAR(50),
    status VARCHAR(20),
    score DECIMAL(3,1),
    cover_url VARCHAR(1000),
    watch_date DATE,
    release_date DATE,
    total_episodes INT,
    current_episode INT,
    last_watch_date DATE,
    memory_text CLOB,
    tags VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_anime_user_id ON sekai_memory_book_anime(user_id);

CREATE TABLE IF NOT EXISTS sekai_memory_book_character_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    anime_id BIGINT,
    character_name VARCHAR(100) NOT NULL,
    image_url VARCHAR(1000),
    reason VARCHAR(255),
    favorite_level TINYINT DEFAULT 5,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_character_user_id ON sekai_memory_book_character_favorite(user_id);

CREATE TABLE IF NOT EXISTS sekai_memory_book_quote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    anime_id BIGINT,
    character_name VARCHAR(100),
    content VARCHAR(500) NOT NULL,
    feeling CLOB,
    tag VARCHAR(50),
    video_url VARCHAR(1000),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_quote_user_id ON sekai_memory_book_quote(user_id);

CREATE TABLE IF NOT EXISTS sekai_memory_book_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    plan_code VARCHAR(50) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    pay_channel VARCHAR(30) NOT NULL DEFAULT 'DEMO',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_memory_order_no UNIQUE (order_no)
);

CREATE INDEX IF NOT EXISTS idx_order_user_id ON sekai_memory_book_order(user_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON sekai_memory_book_order(status);
